name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Install OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          libgtk-3-dev libgtk-3-0 libgtk-3-bin libgtk-3-common
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 80m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
