name: Release

on:
  push:
    branches: [master]

jobs:
  release-build:
    name: Release Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          libgtk-3-dev libgtk-3-0 libgtk-3-bin libgtk-3-common 

      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

  tagged-release:
    needs: [servers-build, clients-build]

    name: "Tagged Release"
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - run: mkdir -p ./builds
      - uses: actions/download-artifact@v3
        with:
          path: ./builds

      - name: Extract Artifacts
        run: |
          mkdir -p ./artifacts

      - name: "Publish Release"
        uses: "bishopfox/action-gh-release@v1"
        with:
          files: |
            ./artifacts/*