name: Build and Release GhostYgg

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build Linux Executable
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev          
          GOOS=linux GOARCH=amd64 go build -v -o GhostYgg-linux ./src/main.go

      - name: Build Windows Executable
        run: GOOS=windows GOARCH=amd64 go build -v -o GhostYgg-windows.exe ./src/main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v1.0.0+${{ github.run_number }}
          release_name: v1.0.0+${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./GhostYgg-linux
            ./GhostYgg-windows.exe
          asset_name: |
            GhostYgg-linux
            GhostYgg-windows.exe
          asset_content_type: application/octet-stream
